name: Move assigned issues into To do

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Planning
          column: Assigned
          repo-token: ${{ secrets.GITHUB_TOKEN }}
